language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  app: siget-mantenimiento
  on:
    branch: develop
  api_key:
    secure: j/d1gjm4mzY5aTAZzGaaLJ9RVCBgWltpRlZEhvhx80W00komvGp1A2IVYtxB/Wk6JqgvKdEgq+U+csulCi5QjIL8Zp9+2gfSjMMLODZwdi82HURovMp07e6jdLcroorYqe2HDB1OvTYbAwJjoQ2aTsyJVWeu9aZpUNhPx6OmpdRQrnMklI8XHsAQFjpGroCsx9pKpgoFoahij/EJJ3JFeuUxzTRsPupr4yw65Hy1R1vsUyw6IqQyi0AWUjbP0pTdAVlL3NPbZmkC7YcpbDSuFkJOLtvdbP5v6NCE8otpjEeiYcvvZftVZByeaojrXqUuTY5K+FeOvb99XA50Gnh5shAe/RnHkHic9s0jOtUzu945RUsZujMn18+kwl9eJ1xhgJ0j6gmUOeN8/TXArWJZbr6kVgytNLP/IECD5TqMLtmpP/2j+FwH97DnSZMtyiRzmXUK4Zz81dIqE14FVCDMVTUdkYP8N1ulFmeKxPTp1qh02m7OlCh4/0JHxfU78Wwro8A0e0dUOf11QW2NbaspSl6t4g3SgT1qJ1SGfhn+RS/nT4SntEQhXnRVAv3GIp8ZAarYWBAQFPA3XkrAn38o1kzyxHOAxj3Mx5704a4O26DF8lAhty8mOKgr7djR6BORJrstAaF5e7PkuHcPQBAEzkNlLY6JiukEn5kFBEdikZ0=
